[book]
authors = ["Robert Masen"]
language = "en"
multilingual = false
src = "src"
title = "Cosock"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/cosock/cosock-book"
edit-url-template = "https://github.com/cosock/cosock-book/edit/main/{path}"
