name: GitHub Pages

on:
  push:
    branches:
      - main
    pull_requests: []
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.18'
      
      - name: Process PlantUML diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: '-tsvg diagrams/*.txt -o ./src/img'
      
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
